apiVersion: v1
kind: ConfigMap
metadata:
  name: vnsearch-config
  namespace: vnsearch
data:
  SPRING_PROFILES_ACTIVE: "prod"
  TZ: "Asia/Ho_Chi_Minh"

  AUTH_JWKS_URI: "http://auth-service:8081/oauth2/jwks"
  AUTH_ISSUER_URI: "http://auth-service:8081"
  AUTH_AUDIENCE: "vnsearch-api"

  APP_CORS_ALLOWED_ORIGINS: "http://localhost:5173"
  APP_RANKING_SCORER: "bm25"

  AUTH_SERVICE_URL: "http://auth-service:8081"
  SEARCH_SERVICE_URL: "http://search-service:8082"
  CRAWLER_SERVICE_URL: "http://crawler-service:8083"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8084"
  HISTORY_SERVICE_URL: "http://history-service:8085"
  DOWNLOADS_SERVICE_URL: "http://downloads-service:8086"
  SETTINGS_SERVICE_URL: "http://settings-service:8087"
  FOOTBALL_SERVICE_URL: "http://football-service:8090"

  REDIS_HOST: "redis"
  MONGO_URI: "mongodb://mongo:27017/vnsearch_history"

  APP_STORAGE_POSTGRES_ENABLED: "true"
  APP_STORAGE_POSTGRES_URL: "jdbc:postgresql://postgres:5432/vnsearch"
  APP_STORAGE_POSTGRES_USER: "vnsearch"

  AUTH_DB_URL: "jdbc:postgresql://postgres:5432/vnsearch_auth"
  AUTH_DB_USER: "vnsearch_auth"
  DOWNLOADS_DB_URL: "jdbc:postgresql://postgres:5432/vnsearch_downloads"
  DOWNLOADS_DB_USER: "vnsearch_downloads"
  SETTINGS_DB_URL: "jdbc:postgresql://postgres:5432/vnsearch_settings"
  SETTINGS_DB_USER: "vnsearch_settings"

  BOOTSTRAP_ADMIN_USERNAME: "admin"
  APP_CRAWLER_BUS: "memory"

  FOOTBALL_DB_HOST: "postgres"
  FOOTBALL_DB_PORT: "5432"
  FOOTBALL_DB_USER: "vnsearch"
  FOOTBALL_DB_NAME: "vnsearch"
  FOOTBALL_PORT: "8090"
  FOOTBALL_DAILY_BUDGET: "95"
  FOOTBALL_API_BASE_URL: "https://v3.football.api-sports.io"
